// Code generated by bpf2go; DO NOT EDIT.
//go:build (386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm) && linux

package trace

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type devdiagEbpfPendingKey struct {
	_         structs.HostLayout
	Pid       uint32
	EventType uint32
}

type devdiagEbpfPendingValue struct {
	_         structs.HostLayout
	EventType uint32
	Family    uint32
	Port      uint32
	Addr4     uint32
	Arg0      [96]uint8
	Arg1      [96]uint8
}

type devdiagEbpfTraceEvent struct {
	_           structs.HostLayout
	TimestampNs uint64
	Pid         uint32
	Ppid        uint32
	EventType   uint32
	_           [4]byte
	Ret         int64
	Family      uint32
	Port        uint32
	Addr4       uint32
	Arg0        [96]uint8
	Arg1        [96]uint8
	_           [4]byte
}

// loadDevdiagEbpf returns the embedded CollectionSpec for devdiagEbpf.
func loadDevdiagEbpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_DevdiagEbpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load devdiagEbpf: %w", err)
	}

	return spec, err
}

// loadDevdiagEbpfObjects loads devdiagEbpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*devdiagEbpfObjects
//	*devdiagEbpfPrograms
//	*devdiagEbpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadDevdiagEbpfObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadDevdiagEbpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// devdiagEbpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type devdiagEbpfSpecs struct {
	devdiagEbpfProgramSpecs
	devdiagEbpfMapSpecs
	devdiagEbpfVariableSpecs
}

// devdiagEbpfProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type devdiagEbpfProgramSpecs struct {
	TracepointSchedProcessFork *ebpf.ProgramSpec `ebpf:"tracepoint_sched_process_fork"`
	TracepointSysEnterBind     *ebpf.ProgramSpec `ebpf:"tracepoint_sys_enter_bind"`
	TracepointSysEnterConnect  *ebpf.ProgramSpec `ebpf:"tracepoint_sys_enter_connect"`
	TracepointSysEnterExecve   *ebpf.ProgramSpec `ebpf:"tracepoint_sys_enter_execve"`
	TracepointSysEnterOpenat   *ebpf.ProgramSpec `ebpf:"tracepoint_sys_enter_openat"`
	TracepointSysExitBind      *ebpf.ProgramSpec `ebpf:"tracepoint_sys_exit_bind"`
	TracepointSysExitConnect   *ebpf.ProgramSpec `ebpf:"tracepoint_sys_exit_connect"`
	TracepointSysExitExecve    *ebpf.ProgramSpec `ebpf:"tracepoint_sys_exit_execve"`
	TracepointSysExitOpenat    *ebpf.ProgramSpec `ebpf:"tracepoint_sys_exit_openat"`
}

// devdiagEbpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type devdiagEbpfMapSpecs struct {
	Events        *ebpf.MapSpec `ebpf:"events"`
	PendingEvents *ebpf.MapSpec `ebpf:"pending_events"`
	TrackedPids   *ebpf.MapSpec `ebpf:"tracked_pids"`
}

// devdiagEbpfVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type devdiagEbpfVariableSpecs struct {
}

// devdiagEbpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadDevdiagEbpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type devdiagEbpfObjects struct {
	devdiagEbpfPrograms
	devdiagEbpfMaps
	devdiagEbpfVariables
}

func (o *devdiagEbpfObjects) Close() error {
	return _DevdiagEbpfClose(
		&o.devdiagEbpfPrograms,
		&o.devdiagEbpfMaps,
	)
}

// devdiagEbpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadDevdiagEbpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type devdiagEbpfMaps struct {
	Events        *ebpf.Map `ebpf:"events"`
	PendingEvents *ebpf.Map `ebpf:"pending_events"`
	TrackedPids   *ebpf.Map `ebpf:"tracked_pids"`
}

func (m *devdiagEbpfMaps) Close() error {
	return _DevdiagEbpfClose(
		m.Events,
		m.PendingEvents,
		m.TrackedPids,
	)
}

// devdiagEbpfVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadDevdiagEbpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type devdiagEbpfVariables struct {
}

// devdiagEbpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadDevdiagEbpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type devdiagEbpfPrograms struct {
	TracepointSchedProcessFork *ebpf.Program `ebpf:"tracepoint_sched_process_fork"`
	TracepointSysEnterBind     *ebpf.Program `ebpf:"tracepoint_sys_enter_bind"`
	TracepointSysEnterConnect  *ebpf.Program `ebpf:"tracepoint_sys_enter_connect"`
	TracepointSysEnterExecve   *ebpf.Program `ebpf:"tracepoint_sys_enter_execve"`
	TracepointSysEnterOpenat   *ebpf.Program `ebpf:"tracepoint_sys_enter_openat"`
	TracepointSysExitBind      *ebpf.Program `ebpf:"tracepoint_sys_exit_bind"`
	TracepointSysExitConnect   *ebpf.Program `ebpf:"tracepoint_sys_exit_connect"`
	TracepointSysExitExecve    *ebpf.Program `ebpf:"tracepoint_sys_exit_execve"`
	TracepointSysExitOpenat    *ebpf.Program `ebpf:"tracepoint_sys_exit_openat"`
}

func (p *devdiagEbpfPrograms) Close() error {
	return _DevdiagEbpfClose(
		p.TracepointSchedProcessFork,
		p.TracepointSysEnterBind,
		p.TracepointSysEnterConnect,
		p.TracepointSysEnterExecve,
		p.TracepointSysEnterOpenat,
		p.TracepointSysExitBind,
		p.TracepointSysExitConnect,
		p.TracepointSysExitExecve,
		p.TracepointSysExitOpenat,
	)
}

func _DevdiagEbpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed devdiagebpf_bpfel.o
var _DevdiagEbpfBytes []byte
